### ISSUE TITLE
Fix profile page layout issue

### ISSUE THREAD

**Issue by slmnio** [slmnio/slmngg-sfc#256]
![image](https://github.com/slmnio/slmngg-sfc/assets/15251071/fd98ff85-7b41-4ea7-beee-f62bd51ac791)

This fixes but it might need to be more subtle on this component
```css
.row {
    width: 100%;
}
```
